name: bhdelni
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^1.1.3
  bloc: ^7.2.1
  flutter_bloc: ^7.3.1
  fluttertoast: ^8.0.9
  shared_preferences: ^2.0.15
  google_sign_in: ^6.1.4
  cupertino_icons: ^1.0.2
  firebase_core: ^2.13.1
  firebase_auth: ^4.6.3
  cloud_firestore: ^4.8.1
  pull_to_refresh: ^2.0.0
  double_back_to_close_app: ^2.1.0
  conditional_builder_null_safety: ^0.0.6
  font_awesome_flutter: ^10.4.0
  scan: ^1.6.0
  images_picker: ^1.2.11
  google_fonts: ^5.1.0
  interactive_bottom_sheet: ^0.1.5
  rounded_loading_button: ^2.1.0
  flutter_switch: ^0.3.2
  intl: ^0.18.1
  nanoid: ^1.0.0
  ticket_material: ^0.3.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.12.0
  flutter_lints: ^2.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/image/logo-_4_.jpg"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/image/logo-_4_.jpg"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/image/logo-_4_.jpg"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/image/logo-_4_.jpg"
flutter:

  uses-material-design: true
  assets:
    - assets/image/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
