// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2RWppFBvfpSflH12tRR2ggTJCpwA8Qmc',
    appId: '1:795684476915:web:b45a539d54d4bfad55e486',
    messagingSenderId: '795684476915',
    projectId: 'bhdelnii',
    authDomain: 'bhdelnii.firebaseapp.com',
    storageBucket: 'bhdelnii.appspot.com',
    measurementId: 'G-5YFR1G7QED',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCp-9tevAo303NNEHJaMYyLepJD5UG3hQY',
    appId: '1:795684476915:android:6e3360981c7b25fa55e486',
    messagingSenderId: '795684476915',
    projectId: 'bhdelnii',
    storageBucket: 'bhdelnii.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5C3GvfgTXpmIHGtoMdwa6fg-XZUhrkEw',
    appId: '1:795684476915:ios:b24b04398b62480655e486',
    messagingSenderId: '795684476915',
    projectId: 'bhdelnii',
    storageBucket: 'bhdelnii.appspot.com',
    iosClientId: '795684476915-kooik0pabvu7moi0mqj392mfuq9fh41f.apps.googleusercontent.com',
    iosBundleId: 'com.example.bhdelni',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5C3GvfgTXpmIHGtoMdwa6fg-XZUhrkEw',
    appId: '1:795684476915:ios:afe0281b6d03b96455e486',
    messagingSenderId: '795684476915',
    projectId: 'bhdelnii',
    storageBucket: 'bhdelnii.appspot.com',
    iosClientId: '795684476915-eglke4g7964likjvj6092b8pqdml9mu4.apps.googleusercontent.com',
    iosBundleId: 'com.example.bhdelni.RunnerTests',
  );
}
